# Generated by Django 6.0.5 on 2026-06-14 22:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrée (Achat/Réassort)'), ('OUT', 'Sortie (Vente)'), ('CORRECTION', 'Correction (Inventaire/Perte)')], max_length=15, verbose_name='Type de mouvement')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motif / Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date du mouvement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Mouvement de Stock',
                'verbose_name_plural': 'Mouvements de Stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
