# Generated by Django 6.0.5 on 2026-06-14 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Stock actuel')),
                ('min_stock_level', models.IntegerField(default=5, verbose_name="Seuil d'alerte mini")),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'État du Stock',
                'verbose_name_plural': 'États des Stocks',
            },
        ),
    ]
